### ISSUE TITLE
Discovery: Develop approach for supporting multiple PHP versions

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#1049]
PHP 7 has some significant performance increases. Drupal 8 supports PHP 7 though Drupal 7 has some issues with tests passing: https://www.drupal.org/node/2454439 
## Tasks
- [ ] Run CircleCI test running PHP 7
- [ ] See if errors generated (if so triage / create separate tickets)
- [ ] Once tests pass spin up a server with PHP 7 and manually test and load test

**Comment by acouch** [comment]
Looks like the initial tests didn't pass and couldn't determine what the issue was. Looks like this would need to be tested locally first.

**Comment by kimwdavidson** [comment]
Let's find out when support for php 5.5 will end

**Comment by grugnog** [comment]
According to https://docs.acquia.com/article/php-55-retirement-faq
"PHP.net will end support for PHP 5.5 in July 2016. As a result, Acquia is ending support for PHP 5.5 in favor of PHP 5.6 on Monday, 2 May 2016" - all of our sites are running on 5.6.

I ran a test with PHP 7.1 and we appear to have only a single error below, plus a bunch of identical warnings from devel_generate: https://circleci.com/gh/GetDKAN/dkan/8652?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
1) DataJsonTest::testDataJson
PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertArrayHasKey() must be a array or ArrayAccess

It seems like fixing these would be a fairly easy task and worth getting ahead of so we can move hosted clients to PHP 7.1 and give the DKAN community time to adjust their hosting also.

We could then run tests on both PHP 5.6 and 7.1 (at least) for a period. I am not sure if we can do that on CircleCI (the 1.0 configs at least), but we have been considering a more generic Docker based test runner anyway, which should accommodate this easily.

**Comment by kimwdavidson** [comment]
Considering discovery completed. Ticket for work here: #2239
