### ISSUE TITLE
Simplified module toggler for non-admins

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2135]
## User story

As a site manager, I want to be able to enable and disable any optional component bundled with DKAN, including both DKAN-specific modules and supported "contrib" modules.

## Background

We are going to skip adopting "apps" for now and add a simpler module enable/disable interface. Create an alternative to the admin/modules page that can be granted to people with lower-level permissions, and provide a clear, intuitive interface for it.

## Additional Info from Dan

I have a pretty fleshed-out POC for this. I have created this module:

https://github.com/NuCivic/module_toggler

I designed it to be re-usable; there is nothing DKAN-specific in that module. The DKAN implementation happens in this hook in dkan_sitewide:

https://github.com/NuCivic/dkan/blob/module-toggler/modules/dkan/dkan_sitewide/dkan_sitewide.module#L260

Some additional styles are added to the theme here:

https://github.com/NuCivic/nuboot_radix/pull/51

You can see it all here:

http://module-toggler.dkan.qa.nuamsdev.com/admin/modules/toggle

The menu path and location in the admin menu should be under DKAN; not sure why that is not appearing.

Additional tests and documentation still needed. The interface itself works, though.

Obviously when we ship this, there would be no "unavailable" modules.

## Sub-Tasks

- [ ] Write tests for module toggler
- [ ] Provide technical documentation for module toggler
- [ ] User documentation
- [ ] Add image support and images for modules
- [ ] Create final MVP module list
- [ ] Put module list into .ini or .yml file

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
