### ISSUE TITLE
Docs aesthetic clean-up

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2291]
- [ ] delete advertisement in sidebar
- [x] change a + a:visited link color to #0071BC
- [x] change .wy-side-nav-search background-color to #0071BC
- [x] add 'Docs' to DKAN at top of leftnav so it says 'DKAN Docs'
- [x] change body color to #212121
- [x] change heading (h1, h2, h3, ...) styles to:

```
font-family: 'Lato', sans-serif;
font-weight: 900;

```

**Comment by dafeder** [comment]
You are supposed to contribute to the RTD project if you are going to remove ads from a docs site. "Gold" memberships start at $5/month, suggested level for a company is $20.

**Comment by lukefretwell** [comment]
@dafeder so RTD is is conditionally open source? :-)

**Comment by kimwdavidson** [comment]
@lukefretwell So should we remove the ads and pay? Contribute time? Or just click through and kill the ads?
