### ISSUE TITLE
Resource upload field not working with s3fs

### ISSUE THREAD

**Issue by digitalsutton** [GetDKAN/dkan#2855]
It appears the file_upload field in Resource does not work correctly with s3fs (when taking over public with s3fs). 

When File Resume is enabled (which it is by default), uploads fail. When that setting is disabled, uploads work as expected (files are uploaded and stored in s3). 

In both cases, Preview and Datastore imports do not work, but download buttons always work (and download the file from s3).

When trying to import to the Datastore, it appears that calls to getUri() return false.

Environment: Pantheon/Lando local

I'm happy to provide more information. In the short term, I'm going to hold off on a planned file migration to s3. 

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1. Install s3fs and configure per docs. Configure to take over the public:// scheme. Confirm s3fs is working for standard file fields.
2. Try to upload a new resource file. You should get a message that the file could not be uploaded.
3. Disable File Resume and try again. File will upload but preview and datastore import will fail. Error message indicates `getTableHeaders()` and displays no file path.

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ ] Allow end user to upload a resource file as normal with the site is configured with s3fs.

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Is there a test for the issue
- [ ] Is there documentation for the issue
- [ ] Are follow up tickets needed

**Comment by kimwdavidson** [comment]
@p51i: This isn't currently on our roadmap, but we'd be happy to review a pull request if you submit one.
