### ISSUE TITLE
Move dkan_datastore variable to a table

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#2877]
Add a brief description about the purpose of the issue.

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1.This variable can get large
2. Locking can get complex and interfere with site operation

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- dkan_datastore is a table (with rows and columns rather than serialized data wherever possible)

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Define table schema
- [ ] Write migration from variable to table
- [ ] Update CRUD functions to use table, remove locking

**Comment by erogray** [comment]
Will require hook update to fix existing sites

**Comment by erogray** [comment]
Closing in favor of https://github.com/GetDKAN/dkan/issues/2685
