### ISSUE TITLE
Undefined Variables and No Hero Background in New Pages

### ISSUE THREAD

**Issue by dyaw-Drexel** [GetDKAN/dkan#2911]
After creating a new page, I get the following errors. Also the Hero background does not show up no matter what.

Notice: Undefined variable: path in include() (line 14 of /var/www/html/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).
Notice: Undefined variable: bg_color in include() (line 14 of /var/www/html/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).
Notice: Undefined variable: tint in include() (line 15 of /var/www/html/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).
Notice: Undefined variable: padding in include() (line 17 of /var/www/html/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1. Create a new page
2. Edit page via "Customize Display" --> Content

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- Fix erros
- Get Hero background to show up

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Is there a test for the issue
- [ ] Is there documentation for the issue
- [ ] Are follow up tickets needed

**Comment by dyaw-Drexel** [comment]
Odd - I just made it the front page and now it works. It however does not in the preview or when it is not the front page.

**Comment by janette** [comment]
Yes @dyaw-Drexel the variables rely on the page being configured as the front page in the site settings. Re-open if you have further issues.
